# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b90fda9d98bb8887199171d0b7c2bba0edbc1e183032d61009bd0ee39e785d59bc43608d68972f60688a7feb87fcb29b799fdc021e79243ba285aaaa41440631

test:
  secret_key_base: 6e3d4e056e810b24cb4c091c95449d5ebc2466edb9e703fe23e1f3b36cc36cdfacf0ef6f90fa0a3bcbc8b2e5cd706e0e90a6538a1c7aeefb1f20669ef81511c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
